### ISSUE TITLE
Plugin prevents translating taxonomy terms

### ISSUE THREAD

**Issue by tnottu** [aucor/polylang-smart-language-select-disabler#2]
When creating a new translation of a taxonomy term, the plugin disables the language select-element. Disabled form elements' values are not submitted with the form so the language value will be empty. So, the translated term will be created on the original (or default?) language instead.

Solution suggestions:

- Perhaps the language select should remain enabled in this view?
- Enable the select before submitting the form
- Add a hidden input with the select's name and value

![disabled-select](https://cloud.githubusercontent.com/assets/4559075/21093441/938a71d6-c05a-11e6-9ba7-203f67b3c2d0.png)

**Comment by TeemuSuoranta** [comment]
I'll look into this. I'll try first enabling the field on submit and if that doesn't work, I will remove disabling when creating new terms. If you need a solution ASAP, you can disable this functionality with a filter on this view.

**Comment by TeemuSuoranta** [comment]
Couldn't get the eventlistener for submit event to work for the form so I had no luck removing the disabled status on submit. I could get other events working just fine and I think submit might have something to do with WP implementation. You can take a shot at it if you feel like it. For now, the quickest solution was to remove the disabling on that view.

Basic input fields have a very nice readonly attribute that would work perfectly if this was a input. It doesn't work for select fields. Adding my own copy for the field seems kind of risky for long-term.

This issue is solved in v 0.1.1 that is now released.
